In [1]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC

In [2]:
data = pd.read_csv('C:/Users/1/Data/SVM/svm-data.csv', header = None)

In [3]:
data

0     1     2
0  0.0  0.70  0.29
1  1.0  0.23  0.55
2  0.0  0.72  0.42
3  0.0  0.98  0.68
4  0.0  0.48  0.39
5  1.0  0.34  0.73
6  0.0  0.44  0.06
7  1.0  0.40  0.74
8  0.0  0.18  0.18
9  1.0  0.53  0.53

In [4]:
X = data.iloc[:, [1, 2]]

In [5]:
Y = data[0]

In [6]:
classifier = SVC(C = 100000, kernel='linear', random_state=241)

In [7]:
classifier.fit(X, Y)

SVC(C=100000, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=241, shrinking=True, tol=0.001,
    verbose=False)

In [8]:
# массив опорных векторов
classifier.support_vectors_

array([[0.98, 0.68],
       [0.48, 0.39],
       [0.53, 0.53]])

In [9]:
# индексы опорных объектов
classifier.support_

array([3, 4, 9])

In [10]:
# количество опорных векторов для каждого из классов
classifier.n_support_

array([2, 1])